# Generated by Django 3.0.4 on 2020-04-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longituge', models.FloatField()),
            ],
        ),
    ]
