# Generated by Django 3.0.4 on 2020-04-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='longituge',
            new_name='longitude',
        ),
    ]
