# Generated by Django 3.0.5 on 2020-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('NOTSENT', 'NOT SENT'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED')], default='NOTSENT', max_length=10),
        ),
    ]
