# Generated by Django 3.0.5 on 2020-05-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200413_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='avatar',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
